GET http://localhost:5000/api/libros
Accept: application/json

###

GET http://localhost:5000/api/libros/1
Accept: application/json

###

POST http://localhost:5000/api/libros
Content-Type: application/json

{
    "titulo": "HasdasdAL",
    "autor": "JasdasdG",
    "resumen": "asdasdasdsad",
    "anio_publicacion": 1997,
    "imagen": "https://images.cdn3.buscalibre.com/fit-in/360x360/ce/e6/cee6ef96dad70d3f599b953f0e50afc7.jpg"
}

###

PUT http://localhost:5000/api/libros/1
Content-Type: application/json

{
    "titulo": "UNA SOMBRA EN LAS BRASAS",
    "autor": "JENNIFER ARMENTROUT",
    "resumen": "El futuro de Seraphena Mierel nunca ha sido suyo. Elegida antes de nacer para cumplir el trato desesperado que aceptó su antepasado para salvar a su gente, Sera debe dejar atrás su vida y ofrecerse al Primigenio de la Muerte como su consorte. Sin embargo, su verdadero destino es el secreto mejor guardado de toda Lasania.",
    "anio_publicacion": 2022,
    "imagen": "https://acdn-us.mitiendanube.com/stores/001/731/769/products/60e8d4c7722c4dfaa43dbe8842810fe11-1442719370a56604da16614437977263-1024-1024.webp"
}

###
DELETE http://localhost:5000/api/libros/4   
