###
GET http://localhost:5000/api/usuarios
Accept: application/json

###
GET http://localhost:5000/api/usuarios/1
Accept: application/json

###
### Crear nuevo usuario
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "nombre": "Usuario",
    "usuario": "otroUser",
    "email": "user2@example.com",
    "password": "nose1234",
    "rol": "usuario"
}

###
PUT http://localhost:5000/api/usuarios/1
Content-Type: application/json

{
    "nombre": "Nombre completo",
    "usuario": "Nombre de usuario",
    "email": "Correo electrónico",
    "password": "Contraseña",
    "rol": "Rol"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "user2@example.com",
    "password": "nose1234"
}

###
DELETE http://localhost:5000/api/usuarios/1